// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojqbivaowhqotvllebvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcWJpdmFvd2hxb3R2bGxlYnZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NjMzMDEsImV4cCI6MjA2OTMzOTMwMX0.Rae8y7ACaJgnX6X9Xa24GIyRM35mnZCBkG8koItFFtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});